language: rust
sudo: required

rust:
    - stable
    - nightly

script:
    - cargo build --all --verbose
    - cargo test --all --verbose
    - cargo doc --all --verbose

after_success:
    - |
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
