[package]
name = "mediawiki-peg-rust"
version = "0.1.0"
authors = ["Valentin Roland <valentin@vroland.de>"]
build = "src/build.rs"

[dependencies]
serde = "1.0"
serde_yaml = "0.7"
serde_derive = "1.0"

[build-dependencies]
serde = "1.0"
serde_yaml = "0.7"
serde_derive = "1.0"
peg = "0.5.4"

