[package]
name = "mediawiki_parser"
version = "0.3.0"
authors = ["Valentin Roland <valentin@vroland.de>"]
build = "build.rs"

[lib]
name = "mediawiki_parser"
path = "src/lib.rs"
doc = true

[features]
default = []
no_position = []

[[bin]]
name = "mwtoast"
path = "src/main.rs"
doc = true

[dependencies]
serde = "1.0"
serde_yaml = "0.7"
serde_derive = "1.0"
argparse = "0.2"
colored = "1.6"

[build-dependencies]
serde = "1.0"
serde_derive = "1.0"
peg = "0.5.4"
serde_yaml = "0.7"

